version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            sudo apt-get install docker

      - run:
          name: start docker
          command: |
            sudo service docker restart

      - run:
          name: run tests
          command: |
            make test
