version: 2
jobs:
  build:
    docker:
      - image: cimg/base

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: run tests
          command: |
            make test
